# configuration file for hako-server

ethereum: 
  contractaddress: /home/okada_shun/hako-server/hkfinance/Hako_address.txt
  networkurl: ws://localhost:7545

mysql: 
  password: /home/okada_shun/.ssh/mysql_password
  user: /home/okada_shun/.ssh/mysql_user
